"""Build an explicitly approximate TMUX6136 channel from IBIS and datasheet data."""

import hashlib
from pathlib import Path

import ecdtools.ibis
import numpy as np


ROOT = Path(__file__).resolve().parents[1]
CIRCUIT = ROOT / "simulations/tia_mcp_check"


def table_string(rows):
    return ", ".join(f"{float(v):.12g}, {float(i):.12g}" for v, i in rows)


def main():
    source = CIRCUIT / "tmux6136.ibs"
    parsed = ecdtools.ibis.load_file(source, transform=True)
    model = parsed.get_model_by_name("input_15p0")
    package = parsed.get_component_by_name("TMUX6136PW").package
    ground = np.asarray(model.gnd_clamp, dtype=float)[:, :2]
    power = np.asarray(model.power_clamp, dtype=float)[:, :2]
    assert model.model_type == "Input" and len(ground) == len(power) == 99
    assert float(model.gnd_clamp_reference.typical) == -15
    assert float(model.power_clamp_reference.typical) == 15
    text = f"""* TMUX6136PWR channel: IBIS input + datasheet-based ANALOG APPROXIMATION.
* NOT an official TI SPICE model. Intended for +/-15 V, 25 C, low-voltage controls.
* Generated by tools/build_tmux6136_model.py; original IBIS remains unchanged.
* IBIS SHA256: {hashlib.sha256(source.read_bytes()).hexdigest()}
* Datasheet: https://www.ti.com/lit/ds/symlink/tmux6136.pdf Rev B, sections 5.5/5.6.
* Each 7-terminal instance is ONE channel, not a physical 7-pin IC.
* Two instances represent the two channels of one TSSOP-16 package.
* SEL=0 connects SB; SEL=1 connects SA. Undefined logic region modeled at 1.4 V.
* No analog-pin clamps, power-off behavior, noise, RF crosstalk or PSRR validation.
* CSOFF to ground plus CD=CON-CSOFF gives lumped selected-node CON at low frequency.
* Capacitance partition, leakage polarity and QJ opposite-edge sign are assumptions.
* QJ=-0.4p is calibrated at VS=0 V; voltage dependence is NOT modeled.
* R_OFF is numerical isolation, NOT inferred from datasheet leakage.
* T_ON/T_OFF reproduce ~66 ns loaded transition / ~40 ns BBM in the test fixture.
.subckt TMUX6136_SPDT SEL SA D SB VSS GND VDD
+ params: RON=120 CSOFF=2.4p CON=5.5p CIN=1.5p
+ IOFF=5p ION=8p R_OFF=1e16 RPD=6Meg
+ T_ON=58n T_OFF=18n QJ=-0.4p VTH=1.4
+ RPKG={float(package.r_pkg.typical):.12g}
+ LPKG={float(package.l_pkg.typical):.12g}
+ CPKG={float(package.c_pkg.typical):.12g}
+ CCOMP={float(model.c_comp.typical):.12g}
*
* IBIS input: actual external rails, all 99 original current samples.
RSEL SEL SEL_MID {{RPKG}}
LSEL SEL_MID SEL_DIE {{LPKG}}
CPIN SEL GND {{CPKG}}
CDIE SEL_DIE GND {{CCOMP}}
* Add only the capacitance missing from the 1.5 pF datasheet total.
CEXTRA SEL_DIE GND {{max(0,CIN-CPKG-CCOMP)}}
RSEL_PD SEL_DIE GND {{RPD}}
BGND SEL_DIE VSS I=table(V(SEL_DIE,VSS), {table_string(ground)})
BPWR SEL_DIE VDD I=table(V(VDD,SEL_DIE), {table_string(power)})
*
* Delayed turn-on / earlier turn-off implements nonoverlapping A/B contacts.
BRAW RAW GND V=if(V(SEL_DIE,GND)>VTH,1,0)
BPOWER POWER_OK GND V=if((V(VDD,GND)>4.9)&(V(GND,VSS)>4.9),1,0)
BA A_EN GND V=V(POWER_OK,GND)*min(delay(V(RAW,GND),T_ON),delay(V(RAW,GND),T_OFF))
BB B_EN GND V=V(POWER_OK,GND)*min(1-delay(V(RAW,GND),T_ON),1-delay(V(RAW,GND),T_OFF))
.model CONTACT SW(Ron=1m Roff={{R_OFF}} Vt=0.5 Vh=0)
RA SA A_PATH {{RON-1m}}
RB SB B_PATH {{RON-1m}}
SA_CONTACT A_PATH D A_EN GND CONTACT
SB_CONTACT B_PATH D B_EN GND CONTACT
CSA SA GND {{CSOFF}}
CSB SB GND {{CSOFF}}
CDRAIN D GND {{max(0,CON-CSOFF)}}
* Offset leakage currents are explicit signed sensitivity parameters.
BLA SA GND I=IOFF*(1-V(A_EN,GND))
BLB SB GND I=IOFF*(1-V(B_EN,GND))
BLD D GND I=ION*(V(A_EN,GND)+V(B_EN,GND))
*
* Smooth charge packet; delivered drain charge = QJ * change(A_EN).
BINJ INJ_RAW GND V=V(A_EN,GND)
RINJ INJ_RAW INJ_FILTER 1k
CINJ INJ_FILTER GND 5p
BQ D GND I=-QJ*ddt(V(INJ_FILTER,GND))
.ends TMUX6136_SPDT
"""
    (CIRCUIT / "TMUX6136_extended.lib").write_text(text)
    print("Built TMUX6136_extended.lib: 99+99 input samples, explicit analog approximation.")


if __name__ == "__main__":
    main()
